import { create } from "zustand";
import { IStaff } from "../Models/Staff";

interface IStaffStore {
  staffs: IStaff[];
}

const useStaffStore = create<IStaffStore>((set) => ({
  staffs: [
    {
      id: "1",
      key: "1",
      avatar: "",
      name: "Nhâm Bổn Tường",
      firstName: "Tường",
      lastName: "Nhâm",
      position: "Software Engineer",
      office: "Văn phòng chính",
      department: "Software",
      staffId: "2007",
      jobType: "Nhân viên chính thức",
      status: "Có hiệu lực",
      bg: "rgb(191, 64, 64)",
    },
    {
      id: "2",
      key: "2",
      avatar: "",
      name: "Nguyễn Hữu An",
      firstName: "An",
      lastName: "Nguyễn",
      position: "Software Engineer",
      office: "Văn phòng chính",
      department: "Software",
      staffId: "2006",
      jobType: "Nhân viên chính thức",
      status: "Có hiệu lực",
      bg: "rgb(45, 210, 210)",
    },
    {
      id: "3",
      key: "3",
      avatar: "",
      name: "Nguyễn Tấn Đức",
      firstName: "Đức",
      lastName: "Nguyễn",
      position: "Software Engineer",
      office: "Văn phòng chính",
      department: "Software",
      staffId: "2005",
      jobType: "Nhân viên chính thức",
      status: "Có hiệu lực",
      bg: "rgb(58, 94, 120)",
    },
    {
      id: "4",
      key: "4",
      avatar: "",
      name: "Nguyễn Kim Quy",
      firstName: "Quy",
      lastName: "Nguyễn",
      position: "Software Engineer",
      office: "Văn phòng chính",
      department: "Software",
      staffId: "2004",
      jobType: "Nhân viên chính thức",
      status: "Có hiệu lực",
      bg: "rgb(134, 113, 45)",
    },
    {
      id: "5",
      key: "5",
      avatar: "",
      name: "Nguyễn Đức Thuận",
      firstName: "Thuận",
      lastName: "Nguyễn",
      position: "Software Engineer",
      office: "Văn phòng chính",
      department: "Software",
      staffId: "2002",
      jobType: "Nhân viên chính thức",
      status: "Có hiệu lực",
      bg: "rgb(191, 130, 64)",
    },
    {
      id: "6",
      key: "6",
      avatar: "",
      name: "Huỳnh Sự",
      firstName: "Sự",
      lastName: "Huỳnh",
      position: "General Manager",
      office: "Văn phòng chính",
      department: "Software",
      staffId: "2001",
      jobType: "Nhân viên chính thức",
      status: "Có hiệu lực",
      bg: "rgb(58, 120, 64)",
    },
    {
      id: "7",
      key: "7",
      avatar: "",
      name: "Võ Duy Tuấn",
      firstName: "Tuấn",
      lastName: "Võ",
      position: "CEO",
      office: "Văn phòng chính",
      department: "BOD",
      staffId: "2000",
      jobType: "Nhân viên chính thức",
      status: "Có hiệu lực",
      bg: "rgb(58, 120, 64)",
    },
  ],
}));

export default useStaffStore;